name: CI Workflow

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build, Test and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Installing Dependencies
        run: yarn install --frozen-lockfile

      - name: Running Linters
        run: yarn lint

      - name: Running Unit Tests
        run: yarn test

      - name: Running Visual Tests
        run: yarn visual-test

      - uses: codecov/codecov-action@v1

      - name: Deploy Storybook
        run: yarn deploy-storybook --ci
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
